# Background and foreground colors
background = #1f130e
foreground = #d7cdb1

# Standard colors
palette = 0=#1f130e
palette = 1=#c7a291
palette = 2=#cdbc92
palette = 3=#d7c69a
palette = 4=#c9a593
palette = 5=#d0ab9a
palette = 6=#d1bf97
palette = 7=#d7cdb1

# Bright colors
palette = 8=#69625f
palette = 9=#edc3ad
palette = 10=#e3c976
palette = 11=#edd37e
palette = 12=#edc5ad
palette = 13=#f0c7b1
palette = 14=#e8cb7c
palette = 15=#ecda9a
