background            #1f130e
foreground            #d7cdb1

# black
color0  #1f130e
color8  #69625f

# red
color1  #c7a291
color9  #edc3ad

# green
color2  #cdbc92
color10 #e3c976

# yellow
color3  #d7c69a
color11 #edd37e

# blue
color4  #c9a593
color12 #edc5ad

# magenta
color5  #d0ab9a
color13 #f0c7b1

#cyan
color6  #d1bf97
color14 #e8cb7c

#white
color7  #d7cdb1
color15 #ecda9a


